### ISSUE TITLE
The program repeatedly gives an error "Please enter a valid user/repository name."

### ISSUE THREAD

**Issue by Cuile** [mandeep/Travis-Encrypt#12]
`
Password:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/travis/encrypt.py", line 49, in retrieve_public_key
    return response.json()['key'].replace(' RSA ', ' ')
KeyError: 'key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/travis-encrypt", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/travis/cli.py", line 60, in cli
    key = retrieve_public_key('{}/{}' .format(username, repository))
  File "/usr/local/lib/python3.7/site-packages/travis/encrypt.py", line 51, in retrieve_public_key
    raise InvalidCredentialsError("Please enter a valid user/repository name.")
travis.encrypt.InvalidCredentialsError: Please enter a valid user/repository name.
`
I looked at the code and it should be "url = 'https://api.travis-ci.org/repos/{}/key' .format(user_repo)" This statement does not work.
I checked developer.travis-ci.com and didn't see this interface. 
Please confirm.

**Comment by mandeep** [comment]
Thanks for the report. Can you show me the full command that you're running? The error looks like you're entering either a username or repository name that doesn't exist.

**Comment by mandeep** [comment]
Should be fixed by 114bc67f4431915d662ce4ba688ad02cdcff3da6
