### ISSUE TITLE
ValueError: Could not unserialize key data.

### ISSUE THREAD

**Issue by dougthor42** [mandeep/Travis-Encrypt#2]
Preface: I'm not sure if this is a bug in `travis-encrypt` or in `cryptography`.

When running on Windows ([WinPython 3.2.2.2](https://github.com/winpython/winpython/releases/tag/1.6.20160828)), I get the `ValueError: Could not unserialize key data.` when trying to run a simple encryption.

### Steps to Reproduce
1. Run on Windows
2. Create a new venv (I called mine `temp` below) and install `travis-encrypt`
3. Run `travis-encrypt dougthor42 ci_setup_testing`
    + the user and repo must exist, else there's a `KeyError`
4. Use `a` for the password when prompted.
5. An exception is raised.

### Versions
+ Windows 10 AU (1607), build 14393.447, 64-bit
+ WinPython 3.2.2.2
+ Python 3.5.2, 64-bit
+ Package versions:
    ```
    (temp) C:\gitlab\github\ci_setup_testing>python -m pip list --format columns
   Package        Version
    -------------- -------
    cffi           1.9.1
    ci-setup-check 1.0
    click          6.6
    cryptography   1.7.1
    idna           2.2
    pip            9.0.1
    pyasn1         0.2.1
    pycparser      2.17
    PyYAML         3.12
    requests       2.12.5
    setuptools     20.10.1
    six            1.10.0
    travis-encrypt 0.4.6
    wheel          0.29.0
    ```

### Exception Stack:
```
(temp) C:\gitlab\github\ci_setup_testing>travis-encrypt dougthor42 ci_setup_testing
Password:
Traceback (most recent call last):
  File "C:\WinPython35_x64\python-3.5.2.amd64\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\WinPython35_x64\python-3.5.2.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\gitlab\github\ci_setup_testing\temp\Scripts\travis-encrypt.exe\__main__.py", line 9, in <module>
  File "c:\gitlab\github\ci_setup_testing\temp\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\gitlab\github\ci_setup_testing\temp\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\gitlab\github\ci_setup_testing\temp\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\gitlab\github\ci_setup_testing\temp\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\gitlab\github\ci_setup_testing\temp\lib\site-packages\travis\encrypt.py", line 62, in cli
    encrypted_password = encrypt_key(key, password.encode())
  File "c:\gitlab\github\ci_setup_testing\temp\lib\site-packages\travis\encrypt.py", line 40, in encrypt_key
    public_key = load_pem_public_key(key.encode(), default_backend())
  File "c:\gitlab\github\ci_setup_testing\temp\lib\site-packages\cryptography\hazmat\primitives\serialization.py", line 24, in load_pem_public_key
    return backend.load_pem_public_key(data)
  File "c:\gitlab\github\ci_setup_testing\temp\lib\site-packages\cryptography\hazmat\backends\multibackend.py", line 314, in load_pem_public_key
    return b.load_pem_public_key(data)
  File "c:\gitlab\github\ci_setup_testing\temp\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1110, in load_pem_public_key
    self._handle_key_loading_error()
  File "c:\gitlab\github\ci_setup_testing\temp\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1325, in _handle_key_loading_error
    raise ValueError("Could not unserialize key data.")
ValueError: Could not unserialize key data.
```

**Comment by FedericoCeratto** [comment]
Same on Debian Linux using cryptography 1.7.1

**Comment by mandeep** [comment]
Hi @dougthor42! Sorry for not seeing this earlier. @FedericoCeratto is right that this has something to do with the way cryptography parses the public key. I'm not sure why the Travis API is sending out the wrong DER format, and if I recall correctly this is an issue that has existed in their API for a while now. I've pushed a patch that removes RSA from the header and footer which seems to fix this issue.
